### ISSUE TITLE
making systray larger

### ISSUE THREAD

**Issue by adrien-barret** [hnbnh/dotfiles#2]
Hello,

I'm trying to make the systray larger. when I have multiple app in the widget icons are so small that they are not "clickable".
What I tried: `wrap_bg(wibox.widget.systray({ screen = s }), { width = dpi(24) }),`
Do you have any idea how to solve that? 

ty

**Comment by hnbnh** [comment]
Sorry but it's been a while since I used `awesomewm`, so I can't provide any idea for that unfortunately :cry:
